needs:
  - rmb@100
displayName: 测试抽奖箱
permanentLimit: 3000
spawnFirework: true
endParticle: hugeexplosion
weightEnabled: true
sound: "random.orb"
descriptions:
  - '内含奖品:'
  - '[ 233 ] * 1天'
  - '[ 466 ] * 1天'
prizes:
  test1:
    displayitem: item@minecraft:stone 0 1
    possibility: 5000
    description: '233'
    broadcast: true
    items:
      - item@minecraft:stone 0 1
    showoriginname: true
    consolecommands: []
    rarity: 平凡
    max_gained_time: 1
    op_commands: []
  test2:
    displayitem: item@minecraft:grass 0 1
    possibility: 20
    description: 没有奖励
    broadcast: true
    items:
      - item@minecraft:stone 0 1
    showoriginname: true
    consolecommands: []
    rarity: 稀有
  test3:
    displayitem: item@minecraft:dirt 0 1
    possibility: 20
    description: 没有奖励
    broadcast: true
    items:
      - item@minecraft:stone 0 1
    showoriginname: true
    consolecommands: []
    rarity: 罕见
  test4:
    displayitem: item@minecraft:cobblestone 0 1
    possibility: 20
    description: 没有奖励
    broadcast: true
    items:
      - item@minecraft:stone 0 1
    showoriginname: true
    consolecommands: []
    rarity: default
  test5:
    displayitem: item@minecraft:planks 0 1
    possibility: 20
    description: 没有奖励
    broadcast: true
    items:
      - item@minecraft:stone 0 1
    showoriginname: true
    consolecommands: []
    rarity: 精良
  test6:
    displayitem: item@minecraft:sapling 0 1
    possibility: 20
    description: 没有奖励
    broadcast: true
    items:
      - item@minecraft:stone 0 1
    showoriginname: true
    consolecommands: []
    rarity: 传说
  test7:
    displayitem: item@minecraft:bedrock 0 1
    description: 没有奖励
    broadcast: true
    items:
      - item@minecraft:stone 0 1
    showoriginname: true
    consolecommands: []
    rarity: 史诗
bonuses:
  test1:
    times: 1
    prize: test1
    items:
      - item@minecraft:stone 0 1
    consolecommands:
      - say test
      - give %player% 1 1