name: LotteryBox
main: glorydark.lotterybox.LotteryBoxMain
version: "1.1.2"
author: glorydark
api: ["1.0.0"]
description: LotteryBox
load: POSTWORLD
depend: ["RcRPG", "QiankunBag", "Tips", "RsNPC", "MagicItem", "EconomyAPI"]
softdepend: ["PlayerPoints"]