name: LotteryBox
main: glorydark.lotterybox.LotteryBoxMain
version: "1.1.2"
author: glorydark
api: ["1.0.0"]
description: LotteryBox
load: POSTWORLD
softdepend: ["Tips", "RsNPC", "MagicItem", "RcRPG", "EconomyAPI", "PlayerPoints"]