name: LotteryBox
main: glorydark.lotterybox.MainClass
version: "1.0.7"
author: glorydark
api: ["1.0.0"]
description: LotteryBox
load: POSTWORLD
softdepend: ["Tips", "RsNPC", "MagicItem", "RcRPG", "EconomyAPI", "PlayerPoints"]